apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "services-app.fullname" . }}-postgres-pvc
  labels:
    app: {{ include "services-app.name" . }}
    tier: postgres
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }} 
