apiVersion: v1
kind: Service
metadata:
  name: {{ include "services-app.fullname" . }}-api
  labels:
    app: {{ include "services-app.name" . }}
    tier: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.debug.inspectPort }}
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    app: {{ include "services-app.name" . }}
    tier: api 
